# Generated by Django 5.2.6 on 2025-11-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mysteries/'),
        ),
        migrations.AddField(
            model_name='mystery',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
