# Generated by Django 5.2.6 on 2025-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mystery_image_mystery_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystery',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
