# Generated by Django 5.2.6 on 2025-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mystery_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystery',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
