# Generated by Django 5.2.6 on 2025-11-08 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mystery_is_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mystery',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='mysteries', to=settings.AUTH_USER_MODEL),
        ),
    ]
