# Generated by Django 5.2.6 on 2025-11-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mystery_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='mystery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.mystery'),
        ),
    ]
