# Generated by Django 5.2.6 on 2025-11-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprogress_mystery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='mystery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.mystery'),
        ),
    ]
