# Generated by Django 5.2.6 on 2025-11-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_review_mystery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mystery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='api.mystery'),
        ),
    ]
