# Generated by Django 5.2.6 on 2025-11-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_question_mystery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mystery',
        ),
    ]
